package utils;

public interface Constants {

	String USER_DESKTOP = System.getProperty("user.home") + "\\Desktop\\";
	String PROJECTS_FILE_PATH = USER_DESKTOP + "projectData.json";
	String STUDENTS_FILE_PATH = USER_DESKTOP + "studentData.json";
	String PROJECT_CLUSTERS_FILE_PATH = USER_DESKTOP + "projectClusterizedData.json";
	String STUDENT_CLUSTERS_FILE_PATH = USER_DESKTOP + "studentClusterizedData.json";
	String STUDENT_HELPERS_FILE_PATH  = USER_DESKTOP + "studentGroupsMatchedWithHelpers.json";
	String STUDENT_PROJECTS_FILE_PATH = USER_DESKTOP + "sutdentGroupsMatchedWithProjects.json";
	
	String PCA_NAME = "PCA";
	String SCA_NAME = "SCA";
	String DPCA_NAME = "DPCA";
	String DSCA_NAME = "DSCA";
	String SPMA_NAME = "SPMA";	
	String SSMA_NAME = "SSMA";
	
	String PCA_SERVICE_NAME = "PROJECT_CLUSTERING_SERVICE";
	String SCA_SERVICE_NAME = "STUDENT_CLUSTERING_SERVICE";
	String DPCA_SERVICE_NAME = "PROJECT_ENVIROMENT_CHANGE_DETECTION_SERVICE";	
	String DSCA_SERVICE_NAME = "STUDENT_ENVIROMENT_CHANGE_DETECTION_SERVICE";
	String SPMA_SERVICE_NAME = "STUDENT_PROJECT_MATCHING_SERVICE";
	String SSMA_SERVICE_NAME = "STUDENT_STUDENT_MATCHING_SERVICE";
	
	String PCA_SCA_CLUSTERING_SERVICE_TYPE = "CLUSTERING_SERVICE_TYPE";
	String DPCA_DSCA_CHANGE_DETECTION_SERVICE_TYPE = "ENVIROMENT_CHANGE_DETECTION_SERVICE_TYPE";
	String SPMA_SSMA_MATCHING_SERVICE_TYPE = "MATCHING_SERVICE_TYPE";
	
	String ONTOLY_NAME = "MAIN_ONTOLOGY";
	
	float EPSILON = 10.0f;
	float DELTA = 5.0f;

}
